### ISSUE TITLE
autogen.sh not working properly on latest repo

### ISSUE THREAD

**Issue by jjj092353** [Gulden/gulden-official#15]
me@pools:/home/coins/gulden-official# ./autogen.sh
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
libtoolize: copying file `build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `build-aux/m4'.
libtoolize: copying file `build-aux/m4/libtool.m4'
libtoolize: copying file `build-aux/m4/ltoptions.m4'
libtoolize: copying file `build-aux/m4/ltsugar.m4'
libtoolize: copying file `build-aux/m4/ltversion.m4'
libtoolize: copying file `build-aux/m4/lt~obsolete.m4'
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
libtoolize: copying file `build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `build-aux/m4'.
libtoolize: copying file `build-aux/m4/libtool.m4'
libtoolize: copying file `build-aux/m4/ltoptions.m4'
libtoolize: copying file `build-aux/m4/ltsugar.m4'
libtoolize: copying file `build-aux/m4/ltversion.m4'
libtoolize: copying file `build-aux/m4/lt~obsolete.m4'
Makefile.am:78: error: CPPFLAGS_FOR_BUILD must be set with '=' before using '+='
Makefile.am:79: error: CFLAGS_FOR_BUILD must be set with '=' before using '+='
autoreconf: automake failed with exit status: 1
me@pools:/home/coins/gulden-official# automake
configure.ac:64: error: required file 'build-aux/compile' not found
configure.ac:64:   'automake --add-missing' can install 'compile'
configure.ac:22: error: required file 'build-aux/config.guess' not found
configure.ac:22:   'automake --add-missing' can install 'config.guess'
configure.ac:22: error: required file 'build-aux/config.sub' not found
configure.ac:22:   'automake --add-missing' can install 'config.sub'
configure.ac:32: error: required file 'build-aux/install-sh' not found
configure.ac:32:   'automake --add-missing' can install 'install-sh'
configure.ac:64: error: required file 'build-aux/ltmain.sh' not found
configure.ac:32: error: required file 'build-aux/missing' not found
configure.ac:32:   'automake --add-missing' can install 'missing'
configure.ac:13: error: required file 'src/config/bitcoin-config.h.in' not found
src/Makefile.am: error: required file 'build-aux/depcomp' not found
src/Makefile.am:   'automake --add-missing' can install 'depcomp'
parallel-tests: error: required file 'build-aux/test-driver' not found
parallel-tests:   'automake --add-missing' can install 'test-driver'
me@pools:/home/coins/gulden-official#

**Comment by mjmacleod** [comment]
What distribution and autotools version?
Works fine on several distributions here, so it is more likely a tooling problem than the scripts being 'broken'

**Comment by jjj092353** [comment]
tell me how to answer your questions and I will - I'm running ubuntu 14.04 - other wallets compile fine on my system

**Comment by mjmacleod** [comment]
Please indicate which version of 14.04 - as some versions are a few years old now..
"lsb_release -rd" to get precise version.

'other wallets' are mostly on code bases that are -years old- so will compile fine on old machines, Gulden has a modern recently updated codebase (as does bitcoin 0.13 which Gulden is based on) and is therefore less tolerant of ancient machines.

**Comment by jjj092353** [comment]
/home/coins/gulden-official# lsb_release -rd
Description:    Ubuntu 14.04.4 LTS
Release:        14.04

**Comment by mjmacleod** [comment]
Hi, you can use the source tarball for older distributions https://github.com/Gulden/gulden-binaries/blob/master/Gulden-1.6.1.tar.gz
The source in this is identical to the github except configured to work with older autotools.

I just verified this to work on an ubuntu 14.04.03 VM so it should be fine for you.

**Comment by jjj092353** [comment]
are you sure that file is complete?

me@pools:/home/coins# wget https://github.com/Gulden/gulden-binaries/blob/master/Gulden-1.6.1.tar.gz
--2016-12-06 12:33:29--  https://github.com/Gulden/gulden-binaries/blob/master/Gulden-1.6.1.tar.gz
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: âGulden-1.6.1.tar.gz.2â

    [ <=>                                                                                                                                     ] 31,315      --.-K/s   in 0.01s   

2016-12-06 12:33:29 (2.05 MB/s) - âGulden-1.6.1.tar.gz.2â saved [31315]

me@pools:/home/coins# tar -zvxf Gulden-1.6.1.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by mjmacleod** [comment]
Should be.
Gulden-1.6.1.tar.gz
7.5Mb
sha256sum 0a3feb3e7ff2dcc9ec388a41edcdf6b8467b3e8a66378970a4cfb4a54e883681

**Comment by mjmacleod** [comment]
wget https://github.com/Gulden/gulden-binaries/raw/master/Gulden-1.6.1.tar.gz

**Comment by jjj092353** [comment]
more problems:

Gulden/auto_checkpoints.cpp:203:13: note: suggested alternative:
In file included from /usr/include/c++/4.8/bits/localefwd.h:41:0,
                 from /usr/include/c++/4.8/string:43,
                 from /usr/include/c++/4.8/stdexcept:39,
                 from ./uint256.h:11,
                 from ./checkpoints.h:8,
                 from Gulden/auto_checkpoints.cpp:11:
/usr/include/c++/4.8/iosfwd:160:34: note:   âstd::ofstreamâ
   typedef basic_ofstream<char>   ofstream;
                                  ^
Gulden/auto_checkpoints.cpp:203:41: error: expected â;â before âcheckpointFileâ
             boost::filesystem::ofstream checkpointFile( GetDataDir() / "autocheckpoints" / "new_checkpoint" );
                                         ^
Gulden/auto_checkpoints.cpp:204:13: error: âcheckpointFileâ was not declared in this scope
             checkpointFile << hashCheckpoint.ToString();
             ^
make[2]: *** [Gulden/libgulden_common_a-auto_checkpoints.o] Error 1
make[2]: Leaving directory `/home/coins/Gulden-1.6.1/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/coins/Gulden-1.6.1/src'
make: *** [all-recursive] Error 1
me@pools:/home/coins/Gulden-1.6.1#

**Comment by mjmacleod** [comment]
Your boost is too old, 1.57 or above is required.

**Comment by mjmacleod** [comment]
Updated https://github.com/Gulden/gulden-official/README.md with list of required dependencies, instructions on how to ensure the right version of boost is available as well as some other troubleshooting for older distros.

Compiling confirmed to work on 14.04.5 (and probably 14.04.4) if following the updated instructions properly.

**Comment by jjj092353** [comment]
I really don;t want to risk upgrading to to Version 16 and this is the only thing I could find on upgrading boost to 1.58 : http://shortrecipes.blogspot.com/2015/02/ubuntu-1404-install-boost-157.html (substitute 58 for 57) do you have any other ideas?

**Comment by mjmacleod** [comment]
There are step by step instructions in our README.md that explain how to compile boost 1.61 in a subdirectory and then use it. (As I already mentioned previously)
These instructions are confirmed to work on Ubuntu 14, there is no reason they should not work for you.
https://github.com/Gulden/gulden-official/README.md

**Comment by mjmacleod** [comment]
Note also there is now a special branch for "old autotools" that would be best for you to use:
https://github.com/Gulden/gulden-official/tree/old_autotools

**Comment by jjj092353** [comment]
getting closer - config went fine

then this and compile failed.

me@pools:/home/coins/Gulden-1.6.1# LD_LIBRARY_PATH=/boost166/lib src/Gulden/
-bash: src/Gulden/: Is a directory

**Comment by jjj092353** [comment]
by the way - using the old_autotools source throws this error on autogen.sh

parallel-tests: installing 'build-aux/test-driver'
aclocal: warning: couldn't open directory 'build-aux/m4': No such file or directory
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
libtoolize: copying file `build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `build-aux/m4'.
libtoolize: copying file `build-aux/m4/libtool.m4'
libtoolize: copying file `build-aux/m4/ltoptions.m4'
libtoolize: copying file `build-aux/m4/ltsugar.m4'
libtoolize: copying file `build-aux/m4/ltversion.m4'
libtoolize: copying file `build-aux/m4/lt~obsolete.m4'
configure.ac:10: installing 'build-aux/compile'
configure.ac:5: installing 'build-aux/config.guess'
configure.ac:5: installing 'build-aux/config.sub'
configure.ac:9: installing 'build-aux/install-sh'
configure.ac:9: installing 'build-aux/missing'
Makefile.am:78: error: CPPFLAGS_FOR_BUILD must be set with '=' before using '+='
Makefile.am:79: error: CFLAGS_FOR_BUILD must be set with '=' before using '+='
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
autoreconf: automake failed with exit status: 1
me@pools:/home/coins/gulden-official#

**Comment by mjmacleod** [comment]
You shouldn't run autogen.sh on the old_autotools branch - you should just run configure and then make - as per the README.md instructions..

**Comment by mjmacleod** [comment]
"LD_LIBRARY_PATH=/boost166/lib src/Gulden/" <- I have no idea what you are trying to do here.

1) Install boost into a fixed directory:
get https://sourceforge.net/projects/boost/files/boost/1.61.0/boost_1_61_0.tar.bz2 && tar -xvf boost_1_61_0.tar.bz2 && cd boost_1_61_0/ && ./bootstrap.sh && ./b2 --prefix=/boost166 cxxflags=-fPIC cflags=-fPIC install

2) Configure the Gulden source
./configure --with-boost=/boost166 -with-incompatible-bdb

3) Buld the Gulden source
make

4) Run GuldenD after build succeeds
LD_LIBRARY_PATH=/boost166  ./src/GuldenD

**Comment by jjj092353** [comment]
compile went ok - but sad to say wallet simply dies on startup.

had to change /boost166 to /boost166/lib because it complained that .so could not be found

no errors recorded in debug.log

**Comment by mjmacleod** [comment]
If it segfaults on startup then you have done something wrong with boost.
I'm going to assume it is segfaulting because you have not given a proper description of what happens...

In this case either you:
1) Failed to pass the -fPIC flags to boost
2) Failed to pass the correct --with-boost= flags to Gulden configure

The only crazy thing here is that you think you can compile software without
(1) A modern system
(2) Having the basic dependencies needed by the software
(3) Reading the instructions
(4) Having enough experience to understand how to work around basic problems with -your- build system.

I am sorry if using other crypto currencies that are all on 4 year old code bases has somehow educated you that there is one recipe that you can follow to build everything, but Gulden is not -other- crypto currencies, our code is not 5 years old and thus it requires the use of more modern libraries/systems.
The usual 'pattern' you have been taught will not work, following our README.md correctly and/or having experience with compiling is required in order to compile our software.

At this point I would point out (again) that there are perfectly good pre-compiled binaries, if compiling is too difficult for you then you should instead stick to those. Compiling is really not necessary and should only be done by those who have a good reason to do so.

**Comment by jjj092353** [comment]
do you have a binary that will work on  ubuntu 14.04 ?

**Comment by mjmacleod** [comment]
64 bit
https://developer.gulden.com/download/161/Gulden161-linux64.tar.xz
32 bit
https://developer.gulden.com/download/161/Gulden161-linux32.tar.xz

**Comment by mjmacleod** [comment]
32 bit
https://developer.gulden.com/download/161/Gulden161-linux32.tar.xz

64 bit
https://developer.gulden.com/download/161/Gulden161-linux64.tar.xz

**Comment by jjj092353** [comment]
binary dies also

:)

**Comment by jjj092353** [comment]
I'm making some progress. I'll get back to you with any issues - thanks

**Comment by jjj092353** [comment]
By the way - what is the HD upgrade? I was asked that.

**Comment by jjj092353** [comment]
I got the wallet working but unfortunately it does not work with MPOS pool software and the MPOS software is throwing errors.

bummer

**Comment by mjmacleod** [comment]
"By the way - what is the HD upgrade? I was asked that."
New 1.6 release changes two major things:
1) Introduces a proper account system into the wallet
2) Introduces HD based wallet (with recovery mnemonics)

When selecting "HD Upgrade" your new wallet will have 2 initial accounts in it.
(a) A legacy account, this is a non HD account that will contain all the non-HD addresses of your previous wallet (from before the upgrade)
(b) A new HD account, this is your first HD account, and any additional accounts created will also be HD.

When selecting to remain "non HD" - the wallet will contain only one account - the legacy account which can be treated like you would treat any other non-HD wallet.

(The HD route is the recommended route)

You can read more about this in our release announcement or ask on our slack for more info.

**Comment by mjmacleod** [comment]
"I got the wallet working but unfortunately it does not work with MPOS pool software and the MPOS software is throwing errors.
bummer"

Unfortunately MPOS makes use of the old deprecated bitcoin account based system, that bitcoin devs have been warning people not to use for yours.
As this system is buggy and as we have introduced a new proper account system in this release we have had to remove the old deprecated system to make way for the new system.

We have tried to keep the RPC for the two account systems the same where possible - so they are mostly compatible, however there are some slight differences - as you are probably seeing with MPOS.
Unfortunately short of modifying MPOS I don't think there is much that can be done here, it's unfortunate but at the same time the new account system brings massive progress so for our project it is ultimately the right route.

**Comment by jjj092353** [comment]
the mpos php code is filing on the line that says:

    if ($block->setConfirmations($aBlock['id'], -1)) {

with an invalid offset


$aAllBlocks = $block->getAllUnconfirmed(max($config['network_confirmations'],$config['confirmations']));

$header = false;
foreach ($aAllBlocks as $iIndex => $aBlock) {
  $strLogMask = "| %10.10s | %10.10s | %-64.64s | %5.5s | %5.5s | %-8.8s";
  $aBlockInfo = $bitcoin->getblock($aBlock['blockhash']);
  // Fetch this blocks transaction details to find orphan blocks
  $aTxDetails = $bitcoin->gettransaction($aBlockInfo['tx'][0]);

  if ($aTxDetails['details'][0]['category'] == 'orphan') {
    // We have an orphaned block, we need to invalidate all transactions for this one
    if ($block->setConfirmations($aBlock['id'], -1)) {
      $status = 'ORPHAN';
    } else {
      $status = 'ERROR';
      $log->logError("    Block became orphaned but unable to update database entries");
    }
    if (!$header) {

**Comment by mjmacleod** [comment]
Sorry I know nothing about MPOS so I can't really make any suggestions there.

If there are specific GuldenD RPC commands that are wrong in some way I can respond to bug reports on those but I unfortunately don't have the time to look into external software.
